enum ActionTypes {
  FETCH_NEWS_LIST = 'News/FETCH_NEWS_LIST',
  FETCH_NEWS = 'News/FETCH_NEWS',

  SET_NEWS_TAB = 'ProfilePortfolio/SET_NEWS_TAB',

  RESET_NEWS_LIST = 'News/RESET_NEWS_LIST',
  SET_NEWS_PAGE = 'News/SET_NEWS_PAGE',

  SET_NEWS_CURRENT = 'ProfilePortfolio/SET_NEWS_CURRENT',

  SET_NEWS_CURRENT_INDEX = 'ProfilePortfolio/SET_NEWS_CURRENT_INDEX',

  FETCH_NEWS_ITEM_COMMENT_LIST_REQUEST = 'News/FETCH_NEWS_ITEM_COMMENT_LIST_REQUEST',

  SET_NEWS_ITEM_COMMENT_PAGE = 'News/SET_NEWS_ITEM_COMMENT_PAGE',

  CREATE_NEWS_COMMENT_LIKE_REQUEST = 'News/CREATE_NEWS_COMMENT_LIKE_REQUEST',

  CREATE_NEWS_COMMENT = 'News/CREATE_NEWS_COMMENT',
  CREATE_NEWS_COMMENT_SUCCESS = 'News/CREATE_NEWS_COMMENT_SUCCESS',
  CREATE_NEWS_COMMENT_FAIL = 'News/CREATE_NEWS_COMMENT_FAIL',

}

export default ActionTypes
