enum ActionTypes {
  FETCH_PROFILE_PORTFOLIO_LIST = 'ProfilePortfolio/FETCH_PROFILE_PORTFOLIO_LIST',
  FETCH_PROFILE_PORTFOLIO = 'ProfilePortfolio/FETCH_PROFILE_PORTFOLIO',
  RESET_PROFILE_PORTFOLIO_FORM = 'ProfilePortfolio/RESET_PROFILE_PORTFOLIO_FORM',
  CREATE_PROFILE_PORTFOLIO = 'ProfilePortfolio/CREATE_PROFILE_PORTFOLIO',
  CREATE_PROFILE_PORTFOLIO_REQUEST = 'ProfilePortfolio/CREATE_PROFILE_PORTFOLIO_REQUEST',
  UPDATE_PROFILE_PORTFOLIO = 'ProfilePortfolio/UPDATE_PROFILE_PORTFOLIO',
  UPDATE_PROFILE_PORTFOLIO_REQUEST = 'ProfilePortfolio/UPDATE_PROFILE_PORTFOLIO_REQUEST',
  DELETE_PROFILE_PORTFOLIO = 'ProfilePortfolio/DELETE_PROFILE_PORTFOLIO',
  DELETE_PROFILE_PORTFOLIO_REQUEST = 'ProfilePortfolio/DELETE_PROFILE_PORTFOLIO_REQUEST',

  SET_PROFILE_PORTFOLIO_TAB = 'ProfilePortfolio/SET_PROFILE_PORTFOLIO_TAB',

  RESET_PROFILE_PORTFOLIO_LIST = 'ProfilePortfolio/RESET_PROFILE_PORTFOLIO_LIST',
  SET_PROFILE_PORTFOLIO_PAGE = 'ProfilePortfolio/SET_PROFILE_PORTFOLIO_PAGE',
}

export default ActionTypes
