enum ActionTypes {
  FETCH_SAVED_SEARCHES = 'SavedSearches/FETCH_SAVED_SEARCHES',
  FETCH_SAVED_SEARCHES_REQUEST = 'SavedSearches/FETCH_SAVED_SEARCHES_REQUEST',
  DELETE_SAVED_SEARCHES = 'SavedSearches/DELETE_SAVED_SEARCHES',
  DELETE_SAVED_SEARCHES_REQUEST = 'SavedSearches/DELETE_SAVED_SEARCHES_REQUEST'
}

export default ActionTypes
