enum ActionTypes {
  FETCH_SAVED_TASK_SEARCHES_REQUEST = 'SavedSearches/FETCH_SAVED_TASK_SEARCHES_REQUEST',
  DELETE_SAVED_TASK_SEARCHES = 'SavedSearches/DELETE_SAVED_TASK_SEARCHES',
  DELETE_SAVED_TASK_SEARCHES_REQUEST = 'SavedSearches/DELETE_SAVED_TASK_SEARCHES_REQUEST',
  RESET_SAVED_SEARCHES_LIST = 'SavedSearches/RESET_SAVED_SEARCHES_LIST',
  FETCH_SAVED_PROFILE_SEARCHES_REQUEST = 'SavedSearches/FETCH_SAVED_PROFILE_SEARCHES_REQUEST',
  DELETE_SAVED_PROFILE_SEARCHES = 'SavedSearches/DELETE_SAVED_PROFILE_SEARCHES',
  DELETE_SAVED_PROFILE_SEARCHES_REQUEST = 'SavedSearches/DELETE_SAVED_PROFILE_SEARCHES_REQUEST',
  SAVED_TASK_SEARCH_CREATE = 'SavedSearches/SAVED_TASK_SEARCH_CREATE',
  SAVED_TASK_SEARCH_CREATE_REQUEST = 'SavedSearches/SAVED_TASK_SEARCH_CREATE_REQUEST',
  SAVED_PROFILE_SEARCH_CREATE = 'SavedSearches/SAVED_PROFILE_SEARCH_CREATE',
  SAVED_PROFILE_SEARCH_CREATE_REQUEST = 'SavedSearches/SAVED_TASK_SEARCH_CREATE_REQUEST',
}

export default ActionTypes
