enum ActionTypes {
  FETCH_FEEDBACKS_TO_PROFILE = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE',
  FETCH_FEEDBACKS_TO_PROFILE_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE_REQUEST',
  FETCH_LATEST_FEEDBACKS_TO_PROFILE = 'ProfileFeedback/FETCH_LATEST_FEEDBACKS_TO_PROFILE',
  FETCH_LATEST_FEEDBACKS_TO_PROFILE_REQUEST = 'ProfileFeedback/FETCH_LATEST_FEEDBACKS_TO_PROFILE_REQUEST',
  CREATE_FEEDBACK_MASTER_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_MASTER_REQUEST',
  CREATE_FEEDBACK_CLIENT_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_CLIENT_REQUEST',
  CREATE_FEEDBACK_SITE = 'ProfileFeedback/CREATE_FEEDBACK_SITE',
  CREATE_FEEDBACK_SITE_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_SITE_REQUEST',
  FEEDBACK_SET_PAGE = 'ProfileFeedback/FEEDBACK_SET_PAGE'

}

export default ActionTypes
