enum ActionTypes {
  FETCH_FEEDBACKS_TO_PROFILE = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE',
  FETCH_FEEDBACKS_TO_PROFILE_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE_REQUEST',
  FETCH_LATEST_FEEDBACKS_TO_PROFILE = 'ProfileFeedback/FETCH_LATEST_FEEDBACKS_TO_PROFILE',
  FETCH_LATEST_FEEDBACKS_TO_PROFILE_REQUEST = 'ProfileFeedback/FETCH_LATEST_FEEDBACKS_TO_PROFILE_REQUEST',
  FEEDBACK_SET_PAGE = 'ProfileFeedback/FEEDBACK_SET_PAGE'
}

export default ActionTypes
