enum ActionTypes {
  FETCH_FEEDBACKS_TO_PROFILE = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE',
  FETCH_FEEDBACKS_TO_PROFILE_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE_REQUEST',
  FETCH_FEEDBACKS_TO_PROFILE_SHORT_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_TO_PROFILE_SHORT_REQUEST',
  FETCH_FEEDBACKS_MAIN_PAGE_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_MAIN_PAGE_REQUEST',
  FETCH_FEEDBACKS_SITE_REQUEST = 'ProfileFeedback/FETCH_FEEDBACKS_SITE_REQUEST',
  CREATE_FEEDBACK_MASTER_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_MASTER_REQUEST',
  CREATE_FEEDBACK_CLIENT_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_CLIENT_REQUEST',
  CREATE_FEEDBACK_SITE = 'ProfileFeedback/CREATE_FEEDBACK_SITE',
  CREATE_FEEDBACK_SITE_REQUEST = 'ProfileFeedback/CREATE_FEEDBACK_SITE_REQUEST',
  FEEDBACK_SET_PAGE = 'ProfileFeedback/FEEDBACK_SET_PAGE',
  RESET_FEEDBACK_LIST = 'ProfileFeedback/RESET_FEEDBACK_LIST'

}

export default ActionTypes
