enum ActionTypes {
  FETCH_EVENT_LIST_REQUEST = 'Event/FETCH_EVENT_LIST_REQUEST',
  FETCH_EVENT_CALENDAR_LIST_REQUEST = 'Event/FETCH_EVENT_CALENDAR_LIST_REQUEST',
  FETCH_EVENT_SIDEBAR_LIST_REQUEST = 'Event/FETCH_EVENT_SIDEBAR_LIST_REQUEST',
  FETCH_EVENT_ONE_REQUEST = 'Event/FETCH_EVENT_ONE_REQUEST',
  RESET_EVENT_FORM = 'Event/RESET_EVENT_FORM',
  RESET_FEEDBACK_EVENT_FORM = 'Event/RESET_FEEDBACK_EVENT_FORM',
  RESET_EVENT_LIST = 'Event/RESET_EVENT_LIST',
  CREATE_EVENT = 'Event/CREATE_EVENT',
  CREATE_EVENT_REQUEST = 'Event/CREATE_EVENT_REQUEST',
  UPDATE_EVENT = 'Event/UPDATE_EVENT',
  UPDATE_EVENT_REQUEST = 'Event/UPDATE_EVENT_REQUEST',
  UPDATE_EVENT_CANCEL = 'Event/UPDATE_EVENT_CANCEL',
  DELETE_EVENT = 'Event/DELETE_EVENT',
  DELETE_EVENT_REQUEST = 'Event/DELETE_EVENT_REQUEST',

  UPDATE_EVENT_EXPENSES = 'Event/UPDATE_EVENT_EXPENSES',

  SET_SUBMIT_EVENT = 'Event/SET_SUBMIT_EVENT',
  SUBMIT_EVENT = 'Event/SUBMIT_EVENT',
  DRAFT_EVENT_REQUEST = 'Event/DRAFT_EVENT_REQUEST',

  SEND_EVENT_REQUEST = 'Event/SEND_EVENT_REQUEST',
  CONFIRM_EVENT_REQUEST = 'Event/CONFIRM_EVENT_REQUEST',
  APPROVE_EVENT_REQUEST = 'Event/APPROVE_EVENT_REQUEST',
  REJECT_EVENT_REQUEST = 'Event/REJECT_EVENT_REQUEST',
  DECLINE_EVENT_REQUEST = 'Event/DECLINE_EVENT_REQUEST',
  COMPLETE_EVENT_REQUEST = 'Event/COMPLETE_EVENT_REQUEST',
  EMPTY_EVENT_UNREAD = 'Event/EMPTY_EVENT_UNREAD',

  CREATE_FEEDBACK_EVENT_MASTER = 'Event/CREATE_FEEDBACK_EVENT_MASTER',
  CREATE_FEEDBACK_EVENT_MASTER_REQUEST = 'Event/CREATE_FEEDBACK_EVENT_MASTER_REQUEST',
  CREATE_FEEDBACK_EVENT_CLIENT = 'Event/CREATE_FEEDBACK_EVENT_CLIENT',
  CREATE_FEEDBACK_EVENT_CLIENT_REQUEST = 'Event/CREATE_FEEDBACK_EVENT_CLIENT_REQUEST',
  EDIT_EVENT_REQUEST = 'Event/EDIT_EVENT_REQUEST',

  CURRENT_EVENT_SET_EDIT_MODE = 'Event/CURRENT_EVENT_SET_EDIT_MODE',

  SET_CURRENT_EVENT_NEXT = 'Event/SET_CURRENT_EVENT_NEXT',
  SET_CURRENT_EVENT_PREVIOUS = 'Event/SET_CURRENT_EVENT_PREVIOUS',

}

export default ActionTypes
