enum ActionTypes {
  CHANGE_PASSWORD = 'ChangePassword/CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS = 'ChangePassword/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR = 'ChangePassword/CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_RESET = 'ChangePassword/CHANGE_PASSWORD_RESET',
}

export default ActionTypes
