enum ActionTypes {
  FETCH_SKILL_LIST = 'Skill/FETCH_SKILL_LIST',
  RESET_SKILL_FORM = 'Skill/RESET_SKILL_FORM',
  CREATE_SKILL = 'Skill/CREATE_SKILL',
  CREATE_SKILL_REQUEST = 'Skill/CREATE_SKILL_REQUEST',
  CREATE_SKILL_CATEGORY = 'Skill/CREATE_SKILL_CATEGORY',
  CREATE_SKILL_CATEGORY_REQUEST = 'Skill/CREATE_SKILL_CATEGORY_REQUEST',
  UPDATE_SKILL_REQUEST = 'Skill/UPDATE_SKILL_REQUEST',
  UPDATE_SKILL = 'Skill/UPDATE_SKILL',
  FETCH_SKILL = 'Skill/FETCH_SKILL',
  DELETE_SKILL = 'Skill/DELETE_SKILL',
  DELETE_SKILL_REQUEST = 'Skill/DELETE_SKILL_REQUEST',
  DELETE_SKILL_CATEGORY = 'Skill/DELETE_SKILL_CATEGORY',
  DELETE_SKILL_CATEGORY_REQUEST = 'Skill/DELETE_SKILL_CATEGORY_REQUEST'
}

export default ActionTypes
