enum ActionTypes {
  FETCH_SKILL_LIST = 'Skill/FETCH_SKILL_LIST',
  CREATE_SKILL = 'Skill/CREATE_SKILL',
  CREATE_SKILL_REQUEST = 'Skill/CREATE_SKILL_REQUEST',
  UPDATE_SKILL_REQUEST = 'Skill/UPDATE_SKILL_REQUEST',
  UPDATE_SKILL = 'Skill/UPDATE_SKILL',
  FETCH_SKILL = 'Skill/FETCH_SKILL',
  DELETE_SKILL = 'Skill/DELETE_SKILL',
  DELETE_SKILL_REQUEST = 'Skill/DELETE_SKILL_REQUEST',
}

export default ActionTypes
