enum ActionTypes {
  FETCH_PROFILE_SEARCH = 'ProfileSearch/FETCH_PROFILE_SEARCH',
  FETCH_PROFILE_SEARCH_STAT_REQUEST = 'ProfileSearch/FETCH_PROFILE_SEARCH_STAT_REQUEST',
  SET_SEARCH_STAT_FILTER = 'ProfileSearch/SET_SEARCH_STAT_FILTER',
  RESET_SEARCH_STAT = 'ProfileSearch/RESET_SEARCH_STAT',
  FETCH_PROFILE_SEARCH_REQUEST = 'ProfileSearch/FETCH_PROFILE_SEARCH_REQUEST',
  RESET_PROFILE_SEARCH = 'ProfileSearch/RESET_PROFILE_SEARCH',
  PROFILE_SEARCH_SET_SORT = 'ProfileSearch/PROFILE_SEARCH_SET_SORT',
  PROFILE_SEARCH_SET_FILTER = 'ProfileSearch/PROFILE_SEARCH_SET_FILTER',
  PROFILE_SEARCH_SET_PAGE = 'ProfileSearch/SET_PAGE',
  PROFILE_SEARCH_SET_USE_LOCATION_FILTER = 'ProfileSearch/PROFILE_SEARCH_SET_USE_LOCATION_FILTER',
  PROFILE_SEARCH_SET_CURRENT_TASK = 'ProfileSearch/PROFILE_SEARCH_SET_CURRENT_TASK',
  PROFILE_SEARCH_SET_ROLE = 'ProfileSearch/PROFILE_SEARCH_SET_ROLE',
}

export default ActionTypes
