enum ActionTypes {
  FETCH_PROFILE_GALLERY_LIST = 'ProfileGallery/FETCH_PROFILE_GALLERY_LIST',
  FETCH_PROFILE_GALLERY = 'ProfileGallery/FETCH_PROFILE_GALLERY',
  RESET_PROFILE_GALLERY_FORM = 'ProfileGallery/RESET_PROFILE_GALLERY_FORM',
  CREATE_PROFILE_GALLERY = 'ProfileGallery/CREATE_PROFILE_GALLERY',
  CREATE_PROFILE_GALLERY_REQUEST = 'ProfileGallery/CREATE_PROFILE_GALLERY_REQUEST',
  UPDATE_PROFILE_GALLERY = 'ProfileGallery/UPDATE_PROFILE_GALLERY',
  UPDATE_PROFILE_GALLERY_REQUEST = 'ProfileGallery/UPDATE_PROFILE_GALLERY_REQUEST',
  DELETE_PROFILE_GALLERY = 'ProfileGallery/DELETE_PROFILE_GALLERY',
  DELETE_PROFILE_GALLERY_REQUEST = 'ProfileGallery/DELETE_PROFILE_GALLERY_REQUEST',

  SET_PROFILE_GALLERY_TAB = 'ProfilePortfolio/SET_PROFILE_GALLERY_TAB',

  RESET_PROFILE_GALLERY_LIST = 'ProfileGallery/RESET_PROFILE_GALLERY_LIST',
  SET_PROFILE_GALLERY_PAGE = 'ProfileGallery/SET_PROFILE_GALLERY_PAGE',

  SET_PROFILE_GALLERY_CURRENT = 'ProfilePortfolio/SET_PROFILE_GALLERY_CURRENT',

  SET_PROFILE_GALLERY_CURRENT_INDEX = 'ProfilePortfolio/SET_PROFILE_GALLERY_CURRENT_INDEX',

  FETCH_PROFILE_GALLERY_ITEM_COMMENT_LIST_REQUEST = 'ProfileGallery/FETCH_PROFILE_GALLERY_ITEM_COMMENT_LIST_REQUEST',

  SET_PROFILE_GALLERY_ITEM_COMMENT_PAGE = 'ProfileGallery/SET_PROFILE_GALLERY_ITEM_COMMENT_PAGE',

  CREATE_PROFILE_GALLERY_COMMENT_LIKE_REQUEST = 'ProfileGallery/CREATE_PROFILE_GALLERY_COMMENT_LIKE_REQUEST',

  CREATE_PROFILE_GALLERY_COMMENT = 'ProfileGallery/CREATE_PROFILE_GALLERY_COMMENT',
  CREATE_PROFILE_GALLERY_COMMENT_SUCCESS = 'ProfileGallery/CREATE_PROFILE_GALLERY_COMMENT_SUCCESS',
  CREATE_PROFILE_GALLERY_COMMENT_FAIL = 'ProfileGallery/CREATE_PROFILE_GALLERY_COMMENT_FAIL',

}

export default ActionTypes
