enum ActionTypes {
  FETCH_PROFILE_CONTACT_LIST = 'Contacts/FETCH_PROFILE_CONTACT_LIST',
  SET_PROFILE_CONTACT_PAGE = 'Contacts/FETCH_PROFILE_CONTACT_LIST',
  RESET_PROFILE_CONTACT_LIST = 'Contacts/RESET_PROFILE_CONTACT_LIST',
  SET_PAGE_PROFILE_CONTACT_LIST = 'Contacts/SET_PAGE_PROFILE_CONTACT_LIST',

  DELETE_SAVED_PEOPLE = 'Contacts/DELETE_SAVED_PEOPLE',
  DELETE_SAVED_PEOPLE_REQUEST = 'Contacts/DELETE_SAVED_PEOPLE_REQUEST',
}

export default ActionTypes
