enum ActionTypes {
  FETCH_MESSAGES_CONTACT_LIST = 'Contacts/FETCH_MESSAGES_CONTACT_LIST',
  SET_MESSAGES_CONTACT_PAGE = 'Contacts/FETCH_MESSAGES_CONTACT_LIST',
  RESET_MESSAGES_CONTACT_LIST = 'Contacts/RESET_MESSAGES_CONTACT_LIST',


}

export default ActionTypes
