enum ActionTypes {
  FETCH_TASK_LIST = 'TaskList/FETCH_TASK_LIST',
  FETCH_TASK_LIST_REQUEST = 'TaskList/FETCH_TASK_LIST_REQUEST',
  RESET_TASK_LIST = 'TaskList/RESET_TASK_LIST',
  TASK_LIST_SET_SORT = 'TaskList/TASK_LIST_SET_SORT',
  TASK_LIST_SET_FILTER = 'TaskList/TASK_LIST_SET_FILTER',
  TASK_LIST_SET_PAGE = 'TaskList/SET_PAGE',
  TASK_LIST_SET_USE_LOCATION_FILTER = 'TaskList/TASK_LIST_SET_USE_LOCATION_FILTER',
  TASK_LIST_SAVE_SEARCH = 'TaskList/TASK_LIST_SAVE_SEARCH',
  TASK_LIST_SAVE_SEARCH_REQUEST = 'TaskList/TASK_LIST_SAVE_SEARCH_REQUEST',
  TASK_LIST_SET_CURRENT_TASK = 'TaskList/TASK_LIST_SET_CURRENT_TASK',
}

export default ActionTypes
