enum ActionTypes {
  RESET_FOLLOWER_LIST = 'Follower/RESET_FOLLOWER_LIST',
  SET_FOLLOWER_PAGE = 'Follower/SET_FOLLOWER_PAGE',
  FETCH_FOLLOWER_LIST = 'Follower/FETCH_FOLLOWER_LIST',
  FETCH_FOLLOWER = 'Follower/FETCH_FOLLOWER',

  CREATE_FOLLOWER = 'Follower/CREATE_FOLLOWER',
  CREATE_FOLLOWER_REQUEST = 'Follower/CREATE_FOLLOWER_REQUEST',
  DELETE_FOLLOWER = 'Follower/DELETE_FOLLOWER',
  DELETE_FOLLOWER_REQUEST = 'Follower/DELETE_FOLLOWER_REQUEST',

}

export default ActionTypes
