enum ActionTypes {
  FETCH_PROFILE_WORK_EXPERIENCE_LIST = 'ProfileWorkExperience/FETCH_PROFILE_WORK_EXPERIENCE_LIST',
  FETCH_PROFILE_WORK_EXPERIENCE = 'ProfileWorkExperience/FETCH_PROFILE_WORK_EXPERIENCE',
  RESET_WORK_EXPERIENCE_FORM = 'ProfileWorkExperience/RESET_WORK_EXPERIENCE_FORM',
  CREATE_WORK_EXPERIENCE = 'ProfileWorkExperience/CREATE_WORK_EXPERIENCE',
  CREATE_WORK_EXPERIENCE_REQUEST = 'ProfileWorkExperience/CREATE_WORK_EXPERIENCE_REQUEST',
  UPDATE_WORK_EXPERIENCE = 'ProfileWorkExperience/UPDATE_WORK_EXPERIENCE',
  UPDATE_WORK_EXPERIENCE_REQUEST = 'ProfileWorkExperience/UPDATE_WORK_EXPERIENCE_REQUEST',
  DELETE_WORK_EXPERIENCE = 'ProfileWorkExperience/DELETE_WORK_EXPERIENCE',
  DELETE_WORK_EXPERIENCE_REQUEST = 'ProfileWorkExperience/DELETE_WORK_EXPERIENCE_REQUEST',
}

export default ActionTypes
