enum ActionTypes {
  RESET_PW_FIRST_STEP_SUBMIT = 'PWERecovery/FIRST_STEP_SUBMIT',
  RESET_PW_FIRST_STEP_ERROR = 'PWERecovery/ERROR',
  RESET_PW_FIRST_STEP_SUCCESS = 'PWERecovery/SUCCESS',
  RESET_PW_SECOND_STEP_SUBMIT = 'PWERecovery/SECOND_STEP_SUBMIT',
  RESET_PW_SECOND_STEP_ERROR = 'PWERecovery/SECOND_STEP_ERROR',
  RESET_PW_SECOND_STEP_SUCCESS = 'PWERecovery/SECOND_STEP_SUCCESS',
  RESET_PW_SET_CODE = 'PWERecovery/RESET_PW_SET_CODE',
  RESET_PW_RESET = 'PWERecovery/RESET_PW_RESET',
  RESET_PW_IS_OPEN = 'PWERecovery/OPEN',
  RESET_PW_IS_OPEN_SUCCESS = 'PWRecovery/OPEN_SUCCESS',
  RESET_PW_FINAL_STEP_SUBMIT = 'PWRecovery/FINAL',
  RESET_PW_FINAL_STEP_ERROR = 'PWRecovery/FINAL_ERROR',
  RESET_PW_FINAL_STEP_SUCCESS = 'PWRecovery/FINAL_SUCCESS'

}

export default ActionTypes
