enum ActionTypes {
  RESET_PW_FIRST_STEP_SUBMIT = 'PWERecovery/FIRST_STEP_SUBMIT',
  RESET_PW_FIRST_STEP_SUCCESS = 'PWERecovery/SUCCESS',
  RESET_PW_SECOND_STEP_SUBMIT = 'PWERecovery/SECOND_STEP_SUBMIT',
  RESET_PW_RESET = 'PWERecovery/RESET_PW_RESET',
  RESET_PW_IS_OPEN = 'PWERecovery/OPEN',
  RESET_PW_IS_OPEN_SUCCESS = 'PWRecovery/OPEN_SUCCESS',
  RESET_PW_FINAL_STEP_SUBMIT = 'PWRecovery/FINAL'

}

export default ActionTypes
