enum ActionTypes {
  SIGN_IN_OPEN = 'Modal/SIGN_IN_OPEN',
  MODAL_CLOSE = 'Modal/MODAL_CLOSE',
  SIGN_UP_OPEN = 'Modal/SIGN_UP_OPEN',
  PHONE_CONFIRM_OPEN = 'Modal/PHONE_CONFIRM_OPEN',
  PASSWORD_RECOVERY_FIRST_STEP_OPEN = 'Modal/PASSWORD_RECOVERY_FIRST_STEP_OPEN',
  PASSWORD_RECOVERY_SUCCESS = 'Modal/PASSWORD_RECOVERY_SUCCESS',
  LOADER_OPEN = 'Modal/LOADER_OPEN',
  CHANGE_PASSWORD_OPEN = 'Modal/CHANGE_PASSWORD_OPEN',
  SKILL_MODAL_OPEN = 'MODAL/SKILL_MODAL_OPEN',
  SKILL_CATEGORY_MODAL_OPEN = 'MODAL/SKILL_CATEGORY_MODAL_OPEN',
  CONFIRM_MODAL_OPEN = 'MODAL/CONFIRM_MODAL_OPEN',
  CHANGE_CONFIRM_DATA = 'MODAL/CHANGE_CONFIRM_DATA',
}

export default ActionTypes
