enum ActionTypes {
  SIGN_IN_OPEN = 'Login/SIGN_IN_OPEN',
  MODAL_CLOSE = 'Login/MODAL_CLOSE',
  SIGN_UP_OPEN = 'Login/SIGN_UP_OPEN',
  PHONE_CONFIRM_OPEN = 'Login/PHONE_CONFIRM_OPEN',
  PASSWORD_RECOVERY_FIRST_STEP_OPEN = 'Login/PASSWORD_RECOVERY_FIRST_STEP_OPEN',
  PASSWORD_RECOVERY_SUCCESS = 'Login/PASSWORD_RECOVERY_SUCCESS'
}

export default ActionTypes
