enum ActionTypes {
  SIGN_IN_OPEN = 'Login/SIGN_IN_OPEN',
  SIGN_IN_CLOSE = 'Login/SIGN_IN_CLOSE',
  SIGN_UP_OPEN = 'Login/SIGN_UP_OPEN',
  SIGN_UP_CLOSE = 'Login/SIGN_UP_CLOSE',
  PHONE_CONFIRM_OPEN = 'Login/PHONE_CONFIRM_OPEN',
  PHONE_CONFIRM_CLOSE = 'Login/PHONE_CONFIRM_CLOSE'
}

export default ActionTypes
