enum ActionTypes {
  FETCH_PROFILE_SETTINGS = 'ProfileSettings/FETCH_PROFILE_SETTINGS',
  UPDATE_PROFILE_SETTINGS = 'ProfileSettings/UPDATE_PROFILE_SETTINGS',
  UPDATE_PROFILE_SETTINGS_REQUEST = 'ProfileSettings/UPDATE_PROFILE_SETTINGS_REQUEST',

}

export default ActionTypes
