enum ActionTypes {
  FETCH_POST_LIST = 'Post/FETCH_POST_LIST',
  FETCH_POST = 'Post/FETCH_POST',
  RESET_POST_FORM = 'Post/RESET_POST_FORM',
  CREATE_POST = 'Post/CREATE_POST',
  CREATE_POST_REQUEST = 'Post/CREATE_POST_REQUEST',
  UPDATE_POST = 'Post/UPDATE_POST',
  UPDATE_POST_REQUEST = 'Post/UPDATE_POST_REQUEST',
  DELETE_POST = 'Post/DELETE_POST',
  DELETE_POST_REQUEST = 'Post/DELETE_POST_REQUEST',

  SET_POST_TAB = 'ProfilePortfolio/SET_POST_TAB',

  RESET_POST_LIST = 'Post/RESET_POST_LIST',
  SET_POST_PAGE = 'Post/SET_POST_PAGE',

  SET_POST_CURRENT = 'ProfilePortfolio/SET_POST_CURRENT',

  SET_POST_CURRENT_INDEX = 'ProfilePortfolio/SET_POST_CURRENT_INDEX',

  FETCH_POST_ITEM_COMMENT_LIST_REQUEST = 'Post/FETCH_POST_ITEM_COMMENT_LIST_REQUEST',

  SET_POST_ITEM_COMMENT_PAGE = 'Post/SET_POST_ITEM_COMMENT_PAGE',

  CREATE_POST_COMMENT_LIKE_REQUEST = 'Post/CREATE_POST_COMMENT_LIKE_REQUEST',

  CREATE_POST_COMMENT = 'Post/CREATE_POST_COMMENT',
  CREATE_POST_COMMENT_SUCCESS = 'Post/CREATE_POST_COMMENT_SUCCESS',
  CREATE_POST_COMMENT_FAIL = 'Post/CREATE_POST_COMMENT_FAIL',

}

export default ActionTypes
