import { action } from "typesafe-actions";

enum ActionTypes {
  TASK_NEGOTIATION_CREATE_TASK_RESPONSE = 'TaskNegotiation/TASK_NEGOTIATION_CREATE_TASK_RESPONSE',
  TASK_NEGOTIATION_CREATE_TASK_RESPONSE_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_CREATE_TASK_RESPONSE_REQUEST',
  TASK_NEGOTIATION_SET_CURRENT_TASK = 'TaskNegotiation/TASK_NEGOTIATION_SET_CURRENT_TASK',
  TASK_NEGOTIATION_SET_CURRENT_MESSAGE = 'TaskNegotiation/TASK_NEGOTIATION_SET_CURRENT_MESSAGE',
  TASK_NEGOTIATION_SET_CURRENT_NEGOTIATION = 'TaskNegotiation/TASK_NEGOTIATION_SET_CURRENT_NEGOTIATION',
  TASK_NEGOTIATION_DECLINE_TASK_RESPONSE = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_TASK_RESPONSE',
  TASK_NEGOTIATION_DECLINE_TASK_RESPONSE_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_TASK_RESPONSE_REQUEST',
  TASK_NEGOTIATION_ACCEPT_TASK_RESPONSE = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_TASK_RESPONSE',
  TASK_NEGOTIATION_ACCEPT_TASK_RESPONSE_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_TASK_RESPONSE_REQUEST',
  TASK_NEGOTIATION_MARK_AS_DONE = 'TaskNegotiation/TASK_NEGOTIATION_MARK_AS_DONE',
  TASK_NEGOTIATION_MARK_AS_DONE_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_MARK_AS_DONE_REQUEST',
  TASK_NEGOTIATION_ACCEPT_MARK_AS_DONE_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_MARK_AS_DONE_REQUEST',
  TASK_NEGOTIATION_EDIT_CONDITIONS = 'TaskNegotiation/TASK_NEGOTIATION_EDIT_CONDITIONS',
  TASK_NEGOTIATION_EDIT_CONDITIONS_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_EDIT_CONDITIONS_REQUEST',
  TASK_NEGOTIATION_ACCEPT_CONDITIONS_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_CONDITIONS_REQUEST',
  TASK_NEGOTIATION_DECLINE_CONDITIONS = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_CONDITIONS',
  TASK_NEGOTIATION_DECLINE_CONDITIONS_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_CONDITIONS_REQUEST',
  TASK_NEGOTIATION_ACCEPT_TASK_OFFER = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_TASK_OFFER',
  TASK_NEGOTIATION_DECLINE_TASK_OFFER_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_TASK_OFFER_REQUEST',
  TASK_NEGOTIATION_DECLINE_TASK_OFFER = 'TaskNegotiation/TASK_NEGOTIATION_DECLINE_TASK_OFFER',
  TASK_NEGOTIATION_ACCEPT_AS_COMPLETED = 'TaskNegotiation/TASK_NEGOTIATION_ACCEPT_AS_COMPLETED',
  TASK_NEGOTIATION_HIRE_MASTER = 'TaskNegotiation/TASK_NEGOTIATION_HIRE_MASTER',
  TASK_NEGOTIATION_HIRE_MASTER_REQUEST = 'TaskNegotiation/TASK_NEGOTIATION_HIRE_MASTER_REQUEST',
  TASK_NEGOTIATION_FETCH_LAST_CONDITIONS = 'TaskNegotiation/TASK_NEGOTIATION_FETCH_LAST_CONDITIONS'

}


export default ActionTypes
