enum ActionTypes {
  FETCH_SAVED_TASKS = 'SavedTasks/FETCH_SAVED_TASKS',
  FETCH_SAVED_TASKS_REQUEST = 'SavedTasks/FETCH_SAVED_TASKS_REQUEST',
  SAVE_TASK_REQUEST = 'SavedTasks/SAVE_TASK_REQUEST',
  RESET_SAVED_TASKS_LIST = 'SavedTasks/RESET_SAVED_TASKS_LIST'
}

export default ActionTypes
