enum ActionTypes {
  FETCH_TASK_USER_STAT = 'UserTask/FETCH_TASK_USER_STAT',
  FETCH_TASK_USER_LIST = 'UserTask/FETCH_TASK_USER_LIST',
  FETCH_TASK_USER_LIST_REQUEST = 'UserTask/FETCH_TASK_USER_LIST_REQUEST',
  RESET_TASK_USER_LIST = 'UserTask/RESET_TASK_USER_LIST',
  TASK_USER_LIST_SET_SORT = 'UserTask/TASK_USER_LIST_SET_SORT',
  TASK_USER_LIST_SET_FILTER = 'UserTask/TASK_USER_LIST_SET_FILTER',
  TASK_USER_LIST_SET_PAGE = 'UserTask/SET_PAGE',
}

export default ActionTypes
