enum ActionTypes {
  REGISTRATION_PHONE_SUBMIT = 'RegistrationPhone/SUBMIT',
  REGISTRATION_PHONE_SET_CALLBACK = 'RegistrationPhone/REGISTRATION_PHONE_SET_CALLBACK',
  REGISTRATION_PHONE_SUBMIT_REQUEST = 'RegistrationPhone/REGISTRATION_PHONE_SUBMIT_REQUEST',
  REGISTRATION_PHONE_RESET = 'RegistrationPhone/RESET',
  REGISTRATION_PHONE_CHANGE = 'RegistrationPhone/REGISTRATION_PHONE_CHANGE',
  REGISTRATION_PHONE_CHANGE_REQUEST = 'RegistrationPhone/REGISTRATION_PHONE_CHANGE_REQUEST',
  REGISTRATION_PHONE_CHANGE_CONFIRM_REQUEST = 'RegistrationPhone/REGISTRATION_PHONE_CHANGE_CONFIRM_REQUEST',
  REGISTRATION_PHONE_CONFIRM = 'RegistrationPhone/REGISTRATION_PHONE_CONFIRM',
}

export default ActionTypes
