enum ActionTypes {
  FETCH_PROFILE_RECOMMENDATION_LIST = 'ProfilePortfolio/FETCH_PROFILE_RECOMMENDATIONS_LIST',
  FETCH_PROFILE_RECOMMENDATION_SHORT_LIST = 'ProfilePortfolio/FETCH_PROFILE_RECOMMENDATION_SHORT_LIST',

  CREATE_PROFILE_RECOMMENDATION = 'ProfilePortfolio/CREATE_PROFILE_RECOMMENDATIONS',
  CREATE_PROFILE_RECOMMENDATION_REQUEST = 'ProfilePortfolio/CREATE_PROFILE_RECOMMENDATIONS_REQUEST',

  DELETE_PROFILE_RECOMMENDATION = 'ProfilePortfolio/DELETE_PROFILE_RECOMMENDATION',
  DELETE_PROFILE_RECOMMENDATION_REQUEST = 'ProfilePortfolio/DELETE_PROFILE_RECOMMENDATION_REQUEST',

  RESET_PROFILE_RECOMMENDATION_LIST = 'ProfilePortfolio/RESET_PROFILE_RECOMMENDATIONS_LIST',
  SET_PROFILE_RECOMMENDATION_PAGE = 'ProfilePortfolio/SET_PROFILE_RECOMMENDATIONS_PAGE',
}

export default ActionTypes
