enum ActionTypes {
  FETCH_PROFILE_TAB_LIST = 'ProfileTab/FETCH_PROFILE_TAB_LIST',
  FETCH_PROFILE_TAB = 'ProfileTab/FETCH_PROFILE_TAB',
  RESET_PROFILE_TAB_FORM = 'ProfileTab/RESET_PROFILE_TAB_FORM',
  CREATE_PROFILE_TAB = 'ProfileTab/CREATE_PROFILE_TAB',
  CREATE_PROFILE_TAB_REQUEST = 'ProfileTab/CREATE_PROFILE_TAB_REQUEST',
  UPDATE_PROFILE_TAB = 'ProfileTab/UPDATE_PROFILE_TAB',
  UPDATE_PROFILE_TAB_REQUEST = 'ProfileTab/UPDATE_PROFILE_TAB_REQUEST',
  DELETE_PROFILE_TAB = 'ProfileTab/DELETE_PROFILE_TAB',
  DELETE_PROFILE_TAB_REQUEST = 'ProfileTab/DELETE_PROFILE_TAB_REQUEST',
}

export default ActionTypes
